export interface ValorantLineup {
  id: string;
  agent: string;
  mapId: string;
  site: "A Site" | "B Site" | "C Site" | "Mid";
  type: "POST_PLANT" | "RECON" | "ONE_WAY" | "ATTACK_ENTRY" | "LOCKDOWN_ULT";
  title: string;
  description: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  throwType: "STANDING" | "JUMP_THROW" | "RUN_THROW";
  bounceCount: 0 | 1 | 2;
  chargeBars: number; // 0 for abilities without charge, 1 to 3 for Sova
  standCoords: { x: number; y: number }; // Percentage on map (0-100)
  landingCoords: { x: number; y: number }; // Percentage on map (0-100)
  aimInstructions: string;
  color: string;
  proPlayerCredit?: string;
}

export const VALORANT_LINEUPS: ValorantLineup[] = [
  {
    id: "sova-ascent-b-recon",
    agent: "Sova",
    mapId: "ascent",
    site: "B Site",
    type: "RECON",
    title: "B-Main Early Aggro Scanner",
    description: "Fires from Attacker B-Lobby to reveal all defenders pushing B-Main and fishing for opening sniper picks.",
    difficulty: "EASY",
    throwType: "STANDING",
    bounceCount: 1,
    chargeBars: 2,
    standCoords: { x: 26, y: 78 },
    landingCoords: { x: 24, y: 52 },
    aimInstructions: "Tuck into the corner of B-Lobby fence. Align the tip of your left shock dart HUD line with the roof antenna.",
    color: "#38bdf8",
    proPlayerCredit: "Leo (FNATIC)",
  },
  {
    id: "sova-ascent-a-default-shock",
    agent: "Sova",
    mapId: "ascent",
    site: "A Site",
    type: "POST_PLANT",
    title: "A-Default Double Shock Dart Kill",
    description: "Fires two synchronized shock darts from A-Main lobby that land simultaneously on the defusing player behind generator.",
    difficulty: "HARD",
    throwType: "STANDING",
    bounceCount: 0,
    chargeBars: 3,
    standCoords: { x: 68, y: 82 },
    landingCoords: { x: 63, y: 36 },
    aimInstructions: "1st Dart: Align crosshair with third cloud gap (1 bar charge). 2nd Dart: Immediately aim at the roof corner and release at full charge.",
    color: "#38bdf8",
    proPlayerCredit: "Derrek (100T)",
  },
  {
    id: "viper-bind-b-snakebite",
    agent: "Viper",
    mapId: "bind",
    site: "B Site",
    type: "POST_PLANT",
    title: "B-Site Container Post-Plant Denial",
    description: "Fires from B-Long fountain into the default plant zone beside the crate, stalling defuse for 12 seconds.",
    difficulty: "MEDIUM",
    throwType: "STANDING",
    bounceCount: 0,
    chargeBars: 0,
    standCoords: { x: 18, y: 82 },
    landingCoords: { x: 26, y: 44 },
    aimInstructions: "Stand on the fountain rim. Place your health bar HUD diamond directly on the crane tip and left click.",
    color: "#10b981",
    proPlayerCredit: "nAts (Team Liquid)",
  },
  {
    id: "viper-bind-a-short-oneway",
    agent: "Viper",
    mapId: "bind",
    site: "A Site",
    type: "ONE_WAY",
    title: "A-Short Teleport Exit One-Way Smoke",
    description: "Lands Poison Cloud on top of the A-Short wooden box, giving defense vision of attacker legs while hiding defender heads.",
    difficulty: "MEDIUM",
    throwType: "JUMP_THROW",
    bounceCount: 0,
    chargeBars: 0,
    standCoords: { x: 55, y: 42 },
    landingCoords: { x: 58, y: 48 },
    aimInstructions: "Wedge against U-Hall doorframe. Look at the lower corner of the solar panel and jump throw at the apex.",
    color: "#10b981",
    proPlayerCredit: "Boaster (FNATIC)",
  },
  {
    id: "killjoy-ascent-b-lockdown",
    agent: "Killjoy",
    mapId: "ascent",
    site: "B Site",
    type: "LOCKDOWN_ULT",
    title: "B-Site Retake Safe Lockdown",
    description: "Places Lockdown device in B-Boathouse wine cellar, completely covering all of B-Site without being wall-bangable from Main.",
    difficulty: "EASY",
    throwType: "STANDING",
    bounceCount: 0,
    chargeBars: 0,
    standCoords: { x: 14, y: 28 },
    landingCoords: { x: 14, y: 28 },
    aimInstructions: "Walk into the far corner of B-Boathouse, face the wooden crate, and activate your ultimate.",
    color: "#fbbf24",
    proPlayerCredit: "Chronicle (FNATIC)",
  },
  {
    id: "brimstone-ascent-a-main-incendiary",
    agent: "Brimstone",
    mapId: "ascent",
    site: "A Site",
    type: "POST_PLANT",
    title: "A-Site Default Incendiary Stall",
    description: "Launches an incendiary molly from safe A-Main cover directly onto the spike planter spot beside Generator.",
    difficulty: "EASY",
    throwType: "STANDING",
    bounceCount: 0,
    chargeBars: 0,
    standCoords: { x: 72, y: 76 },
    landingCoords: { x: 62, y: 35 },
    aimInstructions: "Crouch beside the A-Main bicycle. Align the corner of your mouse icon with the corner of the stone pillar.",
    color: "#ea580c",
    proPlayerCredit: "Zellsis (Sentinels)",
  },
  {
    id: "fade-lotus-a-haunt-roof",
    agent: "Fade",
    mapId: "lotus",
    site: "A Site",
    type: "RECON",
    title: "A-Rubble High Roof Haunt Eye",
    description: "Throws Haunt watcher onto the high temple roof above A-Rubble, instantly spotting defenders playing A-Tree and A-Top.",
    difficulty: "MEDIUM",
    throwType: "JUMP_THROW",
    bounceCount: 0,
    chargeBars: 0,
    standCoords: { x: 76, y: 74 },
    landingCoords: { x: 68, y: 44 },
    aimInstructions: "Stand on the stone steps. Aim right at the center of the carved lotus flower and jump throw.",
    color: "#6366f1",
    proPlayerCredit: "something (Paper Rex)",
  },
  {
    id: "gekko-sunset-b-moshpit",
    agent: "Gekko",
    mapId: "sunset",
    site: "B Site",
    type: "ATTACK_ENTRY",
    title: "B-Pillar Flush Mosh Pit",
    description: "Throws Mosh Pit from B-Main lobby to completely blanket the blind corner behind the central pillar.",
    difficulty: "EASY",
    throwType: "STANDING",
    bounceCount: 0,
    chargeBars: 0,
    standCoords: { x: 28, y: 76 },
    landingCoords: { x: 26, y: 46 },
    aimInstructions: "Align crosshair with the streetlight cable above B-Main entrance and left click.",
    color: "#a3e635",
    proPlayerCredit: "Demon1",
  },
];
